

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/ziroomgateway?useUnicode=true&amp;characterEncoding=UTF-8
  username: root
  password:
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
server:
  port: 8888

  